title: Final Project : Detecting Heart Disease with Random Forrest and Neural Network
description: A template for your AOS C111/204 project site.
logo: /assets/IMG/template_logo.png
show_downloads: true
theme: jekyll-theme-architect
